package cloud.autotests.tests;

import cloud.autotests.helpers.DriverUtils;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Selenide.open;
import static com.codeborne.selenide.Selenide.title;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class GeneratedTests extends TestBase {
    @Test
    @Description("Soon to be implemented by you (or QA.GURU engineers)")
    @DisplayName("intertrust")
    void generatedTest() {
        step("Open 'https://www.intertrust.ru/'", () -> {
            step("// todo: just add selenium action");
        });

        step("shouldHave 'Текст'", () -> {
            step("// todo: just add selenium action");
        });

        step("Open 'https://www.intertrust.ru/about'", () -> {
            step("// todo: just add selenium action");
        });

        step("shouldHave 'Текст'", () -> {
            step("// todo: just add selenium action");
        });

        step("Open 'https://www.intertrust.ru/products'", () -> {
            step("// todo: just add selenium action");
        });

        step("shouldHave 'Текст'", () -> {
            step("// todo: just add selenium action");
        });

        step("Open 'https://www.intertrust.ru/solutions'", () -> {
            step("// todo: just add selenium action");
        });

        step("shouldHave 'Текст'", () -> {
            step("// todo: just add selenium action");
        });

        step("Open 'https://www.intertrust.ru/stoimost'", () -> {
            step("// todo: just add selenium action");
        });

        step("shouldHave 'Текст'", () -> {
            step("// todo: just add selenium action");
        });

        step("Open 'https://www.intertrust.ru/press_center/news/'", () -> {
            step("// todo: just add selenium action");
        });

        step("shouldHave 'Текст'", () -> {
            step("// todo: just add selenium action");
        });

        step("Open 'https://www.intertrust.ru/contacts'", () -> {
            step("// todo: just add selenium action");
        });

        step("shouldHave 'Текст'", () -> {
            step("// todo: just add selenium action");
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://www.intertrust.ru/'", () ->
            open("https://www.intertrust.ru/"));

        step("Page title should have text 'Электронный документооборот: система электронного документооборота (СЭД) - автоматизация бизнес процессов -Компания «ИнтерТраст»'", () -> {
            String expectedTitle = "Электронный документооборот: система электронного документооборота (СЭД) - автоматизация бизнес процессов -Компания «ИнтерТраст»";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://www.intertrust.ru/'", () ->
            open("https://www.intertrust.ru/"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}